export class Toolboxtalks {
    // tslint:disable-next-line:variable-name
    resource_plan: boolean;
    // tslint:disable-next-line:variable-name
    createdAt: Date;
    // tslint:disable-next-line:variable-name
    necessary_proc: boolean;
    // tslint:disable-next-line:variable-name
    gov_monitor: boolean;
    // tslint:disable-next-line:variable-name
    h2s_training: boolean;
    // tslint:disable-next-line:variable-name
    hard_hat: boolean;
    // tslint:disable-next-line:variable-name
    boots: boolean;
    // tslint:disable-next-line:variable-name
    coverwalls: boolean;
    // tslint:disable-next-line:variable-name
    hearing_protection: boolean;
    // tslint:disable-next-line:variable-name
    other_ppe: boolean;
    // tslint:disable-next-line:variable-name
    scope: boolean;
    material: boolean;
    // tslint:disable-next-line:variable-name
    traffic_control: boolean;
    // tslint:disable-next-line:variable-name
    mobile_phones: boolean;
    // tslint:disable-next-line:variable-name
    incident_reporting: boolean;
    // tslint:disable-next-line:variable-name
    smoking: boolean;
    // tslint:disable-next-line:variable-name
    speed_limits: boolean;
    // tslint:disable-next-line:variable-name
    first_aid_kit: boolean;
    // tslint:disable-next-line:variable-name
    emergency: boolean;
    // tslint:disable-next-line:variable-name
    regulatory_requests: boolean;
    // tslint:disable-next-line:variable-name
    fire_permit: boolean;
    // tslint:disable-next-line:variable-name
    task_hazard: boolean;
    // tslint:disable-next-line:variable-name
    site_work_permit: boolean;
    // tslint:disable-next-line:variable-name
    ground_disturbance: boolean;
    // tslint:disable-next-line:variable-name
    other_permit_forms: boolean;
    // tslint:disable-next-line:variable-name
    fire_extinguishers: boolean;
    // tslint:disable-next-line:variable-name
    prestat_check: boolean;
    // tslint:disable-next-line:variable-name
    back_up_alarm: boolean;
    // tslint:disable-next-line:variable-name
    positive_air_shafts: boolean;
    // tslint:disable-next-line:variable-name
    people_onboard: number;
    // tslint:disable-next-line:variable-name
    wall_heads: boolean;
    // tslint:disable-next-line:variable-name

    // tslint:disable-next-line:variable-name
    others_on_site: boolean;
    // tslint:disable-next-line:variable-name
    third_party_support: boolean;
    signs: boolean;
}
